import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { NgModule } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NbActionsModule, NbCardModule, NbContextMenuModule, NbIconModule, NbInputModule, NbSelectModule, NbUserModule, NbTabsetModule, NbFormFieldModule, NbButtonModule, NbCheckboxModule, NbRouteTabsetModule, NbToggleModule, NbTagModule, NbTooltipModule, NbToastrModule, NbStepperModule, NbAccordionModule, NbDialogModule, NbLayoutModule, NbButtonGroupModule, NbChatModule, NbRadioModule, NbBadgeModule, NbAutocompleteModule, NbDatepickerModule, NbProgressBarModule } from '@nebular/theme';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    NbIconModule,
    NbSelectModule,
    NbActionsModule,
    NbUserModule,
    NbContextMenuModule,
    NbInputModule,
    NbCardModule,
    NbTabsetModule,
    NbFormFieldModule,
    NbButtonModule,
    FormsModule,
    NbCheckboxModule,
    HttpClientModule,
    NbRouteTabsetModule,
    ReactiveFormsModule,
    NbToggleModule,
    NbTagModule,
    NbTooltipModule,
    NbToastrModule,
    NbStepperModule,
    NbAccordionModule,
    NbDialogModule,
    NbChatModule,
    NbLayoutModule,
    NbButtonGroupModule,
    NbDialogModule.forChild(),
    NbDatepickerModule.forRoot(),
    NbRadioModule,
    NbBadgeModule,
    NbAutocompleteModule,
    NbProgressBarModule
  ],
  providers: [],
  exports: [
    CommonModule,
    NbIconModule,
    NbSelectModule,
    NbActionsModule,
    NbUserModule,
    NbContextMenuModule,
    NbInputModule,
    NbCardModule,
    NbTabsetModule,
    NbFormFieldModule,
    NbButtonModule,
    FormsModule,
    NbCheckboxModule,
    HttpClientModule,
    NbRouteTabsetModule,
    ReactiveFormsModule,
    NbToggleModule,
    NbTagModule,
    NbTooltipModule,
    NbToastrModule,
    NbStepperModule,
    NbAccordionModule,
    NbDialogModule,
    NbChatModule,
    NbProgressBarModule,
    NbRadioModule,
    NbBadgeModule,
    NbDatepickerModule,
    NbAutocompleteModule
  ],
})
export class SharedModule { }
